#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

# CHANGING BORDER COLORS
# normal_border_color
bspc config focused_border_color "#52b0ef"
bspc config active_border_color "#52b0ef"

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#executing polybar
polybar example &
# /home/anand/.config/polybar/launch.sh

# executing feh for background
feh --bg-fill $HOME/Pictures/imagestuff/savedpictures/arch.png

#spawning the greenclip daemon
greenclip daemon &
 
# touchegg
touchegg &
 
# auto-cpufreq
auto-cpufreq &

# dunst 
/usr/bin/dunst &

# executing polkit gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#playerctl 
# playerctld daemon 

#allowing mouse to change focus
bspc config focus_follows_pointer true


