#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

# CHANGING BORDER COLORS
# normal_border_color
# bspc config focused_border_color "#52b0ef"
# bspc config active_border_color "#52b0ef"

# bspc config focused_border_color "#F44747"
# bspc config active_border_color "#F44747"

bspc config focused_border_color "#ff0000"
bspc config active_border_color "#ff0000"

bspc config border_width         5
# bspc config window_gap          12
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# setting zathura for tiling mode
bspc rule -a Zathura state=tiled

#executing polybar
polybar -r example &
# /home/anand/.config/polybar/launch.sh
nm-applet &

# executing feh for background
feh --bg-fill $HOME/Pictures/imagestuff/savedpictures/trains.jpg

#spawning the greenclip daemon
greenclip daemon &
 
# touchegg
touchegg &
 
# auto-cpufreq
auto-cpufreq &

# setting r rate(i copy pasted it here from .xprofile and deleted it from there)
xset r rate 200 70

# dunst 
/usr/bin/dunst &

#for setting the pointer
# xsetroot -cursor_name left_ptr &

# executing polkit gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#playerctl 
# playerctld daemon 

#allowing mouse to change focus
bspc config focus_follows_pointer true

#bspswallow 
pgrep bspswallow || bspswallow &

#picom
# picom -b --config $HOME/.config/picom/picom.conf &
picom &
